name: compile code and tests

on:
  push:
    branches: [ main, develop, issue15_CI_workflow, upstream ]
  pull_request:
    branches: [ main, develop,  issue15_CI_workflow ]

jobs:
  build-on-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: installs
      run: |
        brew install netcdf
        brew install boost
        brew install catch2
        brew install cmake
    - name: make
      run: |
        cmake .
        make VERBOSE=1
